name: Update Draft Release
"on":
    push:
        branches:
            - main
jobs:
    update:
        name: Update Draft Release
        runs-on:
            - ubuntu-latest
        steps:
            - id: release-drafter
              uses: release-drafter/release-drafter@v5
              env:
                GITHUB_TOKEN: ${{ '{{'|safe }} secrets.AMP_BUILDPACKS_BOT_GITHUB_TOKEN {{ '}}'|safe }}
            - name: Docker login ghcr.io
              if: ${{ '{{'|safe }} (github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork) && (github.actor != 'dependabot[bot]') {{ '}}'|safe }}
              uses: docker/login-action@v2
              with:
                password: ${{ '{{'|safe }} secrets.AMP_BUILDPACKS_BOT_GITHUB_TOKEN {{ '}}'|safe }}
                registry: ghcr.io
                username: ${{ '{{'|safe }} github.actor {{ '}}'|safe }}
            - uses: actions/checkout@v3
            - name: Update draft release with buildpack information
              uses: docker://ghcr.io/paketo-buildpacks/actions/draft-release:main
              with:
                github_token: ${{ '{{'|safe }} secrets.AMP_BUILDPACKS_BOT_GITHUB_TOKEN {{ '}}'|safe }}
                release_body: ${{ '{{'|safe }} steps.release-drafter.outputs.body {{ '}}'|safe }}
                release_id: ${{ '{{'|safe }} steps.release-drafter.outputs.id {{ '}}'|safe }}
                release_name: ${{ '{{'|safe }} steps.release-drafter.outputs.name {{ '}}'|safe }}
                release_tag_name: ${{ '{{'|safe }} steps.release-drafter.outputs.tag_name {{ '}}'|safe }}
